### ISSUE TITLE
Cannot compile on ubuntu 14.04

### ISSUE THREAD

**Issue by voldyman** [wanproxy/wanproxy#6]
i tried compiling wanproxy on ubuntu 14.04 and get the following error

```
clang++ -I../../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o aes128-cbc-speed1.o aes128-cbc-speed1.cc
aes128-cbc-speed1.cc:58:22: error: no matching function for call to 'callback'
                callback_action_ = callback(this, &CryptoSpeed::callback_complete)->schedule();

```

clang version
```
─> clang++ --version
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by caladri** [comment]
Please run `make` in `programs/wanproxy` as described on the website, or see issue #3.
