### ISSUE TITLE
Can't build on ubuntu 17.10

### ISSUE THREAD

**Issue by slesru** [wanproxy/wanproxy#16]
Hello!

~/wanproxy-master/programs$ make
==> diskdup (all)
make[1]: вход в каталог «/home/dm/wanproxy-master/programs/diskdup»
g++ -I../.. -Wno-deprecated -Wnon-virtual-dtor -include common/common.h -pipe -O -g -W -Wall -Wno-system-headers -Wno-uninitialized -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Wreorder -DTHREADS -c -o diskdup.o diskdup.cc
diskdup.cc: In member function ‘void DiskDup::read_complete(Event, bool)’:
diskdup.cc:97:11: error: ‘struct Event’ has no member named ‘buffer_’
    if (!e.buffer_.empty()) {
           ^~~~~~~

Thank you!

**Comment by slesru** [comment]
btw, the same problem on latest centos 7

**Comment by caladri** [comment]
Please build in programs/wanproxy, not in the programs subdirectory.
